name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          pwd
          ls
          # wget https://crowdin.com/backend/download/project/alist/zh-CN.zip 
          # unzip zh-CN.zip
          # node ./scripts/i18n.mjs
          # pnpm install
          # pnpm build

      # - name: Upload to server
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
      #     ARGS: "-avz --delete"
      #     SOURCE: dist/
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
